apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "study-platform.fullname" . }}-api-dataprotection
  labels:
    {{- include "study-platform.selectorLabels" (dict "root" . "component" "api") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.api.dataProtectionKeys.storage }}
