// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using StudyPlatform.Infrastructure.Data;

#nullable disable

namespace StudyPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323000000_AddTranscriptToDocument")]
    partial class AddTranscriptToDocument
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
