// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using StudyPlatform.Infrastructure.Data;

#nullable disable

namespace StudyPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323100000_AddGlossaryTerms")]
    partial class AddGlossaryTerms
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
