namespace StudyPlatform.Domain.Interfaces;

public interface IUnitOfWork : IDisposable
{
    IUserRepository Users { get; }
    ICourseRepository Courses { get; }
    IDocumentRepository Documents { get; }
    IOtpRepository Otps { get; }
    IRefreshTokenRepository RefreshTokens { get; }
    IQuizRepository Quizzes { get; }
    IFlashcardRepository Flashcards { get; }
    INoteRepository Notes { get; }
    IChatMessageRepository ChatMessages { get; }
    IAnalyticsRepository Analytics { get; }
    IQuizSubmissionRepository QuizSubmissions { get; }
    IVideoRepository Videos { get; }
    IGlossaryTermRepository GlossaryTerms { get; }
    IFeedbackRepository Feedbacks { get; }
    IShareTokenRepository ShareTokens { get; }
    IGlossaryMasteredRepository GlossaryMastered { get; }
    IWorkedProblemRepository WorkedProblems { get; }
    IWorkedProblemAttemptRepository WorkedProblemAttempts { get; }
    IWorkedProblemMasteredRepository WorkedProblemMastered { get; }
    IDocumentAnnotationRepository DocumentAnnotations { get; }
    IStudyGroupRepository StudyGroups { get; }
    IStudyGroupMemberRepository StudyGroupMembers { get; }
    IStudyGroupSharedCourseRepository StudyGroupSharedCourses { get; }
    IGroupChatMessageRepository GroupChatMessages { get; }
    IConceptLinkRepository ConceptLinks { get; }
    IFlashcardSrsDataRepository FlashcardSrs { get; }
    IStudySessionRepository StudySessions { get; }
    IMistakeEntryRepository MistakeEntries { get; }
    IExamPlanRepository ExamPlans { get; }
    IQuizBattleRepository QuizBattles { get; }
    IGroupAssignmentRepository GroupAssignments { get; }
    IFlashcardReviewLogRepository FlashcardReviewLogs { get; }
    IStreakCoverDayRepository StreakCoverDays { get; }
    IUserCalendarFeedRepository UserCalendarFeeds { get; }
    ICourseAudioOverviewRepository CourseAudioOverviews { get; }
    IGroupNoteRepository GroupNotes { get; }
    IAiJobRepository AiJobs { get; }
    IAiUsageRepository AiUsage { get; }
    IOrganizationRepository Organizations { get; }
    IOrganizationMemberRepository OrganizationMembers { get; }
    IClassroomRepository Classrooms { get; }
    IClassroomEnrollmentRepository ClassroomEnrollments { get; }
    IClassroomCourseRepository ClassroomCourses { get; }
    ISubscriptionRepository Subscriptions { get; }
    IRubricRepository Rubrics { get; }
    IEssaySubmissionRepository EssaySubmissions { get; }
    Task<int> SaveChangesAsync(CancellationToken cancellationToken = default);
}
